HalloDoc Project/Controllers/GuestController.cs
using BAL.Interfaces;
using DAL.DataContext;
using DAL.DataModels;
using DAL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using BAL.Repository;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Web.Optimization;

namespace HalloDoc_Project.Controllers
{
    public class GuestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly IConfiguration _config;
        private readonly IRequestRepo _patient_Request;
        private readonly IJwtToken _jwtToken;
        private readonly IResetPasswordService _resetPasswordService;
        private readonly IEmailService _emailService;
        private readonly IPasswordHasher _passwordHasher;
        private readonly IAgreement _agreement;
        private readonly INotyfService _notyf;
        public GuestController(ApplicationDbContext context, IWebHostEnvironment environment, IConfiguration config, IRequestRepo request, IJwtToken token, IResetPasswordService resetPasswordService, IEmailService emailService, IPasswordHasher passwordHasher, IAgreement agreement, INotyfService notyf)
        {
            _context = context;
            _environment = environment;
            _config = config;
            _patient_Request = request;
            _jwtToken = token;
            _resetPasswordService = resetPasswordService;
            _emailService = emailService;
            _passwordHasher = passwordHasher;
            _agreement = agreement;
            _notyf = notyf;
        }

        //Only ResetPassword is not taken into the three tier architecture otherwise everything from GuestController is in three tier architecture.
        public IActionResult Agree(int Requestid)
        {
            _agreement.AgreementAccepted(Requestid);
            return RedirectToAction("login_page", "Guest");
        }
        public IActionResult CancelAgreement(int Requestid, string Notes)
        {
            _agreement.AgreementRejected(Requestid, Notes);
            return RedirectToAction("login_page", "Guest");
        }
        public IActionResult ReviewAgreement(int ReqId)
        {
            var user = _context.Requestclients.FirstOrDefault(x => x.Requestid == ReqId);
            if (user != null)
            {
                ReviewAgreementViewModel reviewmodel = new()
                {
                    reqID = ReqId,
                    PatientName = user.Firstname + " " + user.Lastname
                };
                return View(reviewmodel);
            }
            return RedirectToAction("submit_request_page");
        }
        [HttpPost]
        public JsonResult CheckEmail(string email)
        {
            bool emailExists = _context.Users.Any(u => u.Email == email);
            return Json(new { exists = emailExists });
        }

        public IActionResult PatientAccountSetupPage(string token)
        {
            try
            {
                string emailid = _resetPasswordService.ValidateToken(token);
                Aspnetuser? user = _context.Aspnetusers.FirstOrDefault(user => user.Email == emailid);

                PatientSetupViewModel PatientData = new()
                {
                    UserName = user.Email
                };
                if (user != null)
                {
                    return View(PatientData);
                }
                else
                {
                    return RedirectToAction("submit_request_page", "Guest");
                }
            }
            catch (Exception ex)
            {
                    return Content("Exception :- " + ex);
            }
        }
        [HttpPost]
        public IActionResult PatientAccountSetupPage(PatientSetupViewModel patientData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Aspnetuser user = _context.Aspnetusers.FirstOrDefault(user => user.Email == patientData.UserName);
                    if (patientData.Password == patientData.ConfirmPassword)
                    {
                        user.Passwordhash = _passwordHasher.GenerateSHA256(patientData.Password);
                    }
                    _context.Aspnetusers.Update(user);
                    _context.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                _notyf.Error(ex.Message);
            }
            return RedirectToAction("login_page", "Guest");
        }

        #region GUEST VIEWS
        public IActionResult PrivacyPolicy()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AccessDenied()
        {
            return View();
        }
        public IActionResult submit_request_page()
        {
            return View();
        }
        public IActionResult patient_submit_request_screen()
        {
            return View();
        }
        public IActionResult SessionExpired()
        {
            return View();
        }
        public IActionResult TermsAndConditions()
        {
            return View();
        }
        #endregion

        #region BUSINESS REQUEST
        [HttpGet]
        public IActionResult Business_Info()

        {
            BusinessModel model = new BusinessModel();
            model.Regions = _context.Regions.ToList();
            return View(model);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Business_Info(BusinessModel bm)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var jwtToken = _resetPasswordService.GenerateJWTTokenForPassword(bm.PatientEmail);
                    var SetupLink = Url.Action("PatientAccountSetupPage", "Guest", new { token = jwtToken }, Request.Scheme);
                    _patient_Request.BRequest(bm, SetupLink ?? " ");
                    return RedirectToAction("Business_Info", "Guest");
                }
                bm.Regions = _context.Regions.ToList();
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
            }
            return View(bm);
        }
        #endregion

        #region CONCIERGE REQUEST
        [HttpGet]
        public IActionResult Concierge_info()
        {
            ConciergeModel model = new ConciergeModel();
            model.Regions = _context.Regions.ToList();
            return View(model);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Concierge_info(ConciergeModel cm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var jwtToken = _resetPasswordService.GenerateJWTTokenForPassword(cm.PatientEmail);
                    var SetupLink = Url.Action("PatientAccountSetupPage", "Guest", new { token = jwtToken }, Request.Scheme);
                    _patient_Request.CRequest(cm, SetupLink ?? " ");
                    return RedirectToAction("Concierge_info", "Guest");
                }
                cm.Regions = _context.Regions.ToList();
            }
            catch(Exception ex)
            {
                _notyf.Error(ex.Message);
            }
            
            return View(cm);
        }
        #endregion

        #region FAMILY FRIEND REQUEST
        public IActionResult Friend_family()
        {
            FamilyFriendModel familyFriendModel = new FamilyFriendModel();
            familyFriendModel.PatientRegions = _context.Regions.ToList();
            return View(familyFriendModel);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Friend_family(FamilyFriendModel fmfr)
        {
            string path = _environment.WebRootPath;
            try
            {
                if (ModelState.IsValid)
                {
                    var uniqueid = Guid.NewGuid().ToString();
                    var jwtToken = _resetPasswordService.GenerateJWTTokenForPassword(fmfr.PatientModel.Email);
                    var SetupLink = Url.Action("PatientAccountSetupPage", "Guest", new { token = jwtToken }, Request.Scheme);
                    _patient_Request.FRequest(fmfr, uniqueid, path, SetupLink ?? " ");
                    return RedirectToAction("Friend_Family", "Guest");

                }
                fmfr.PatientRegions = _context.Regions.ToList();
                _notyf.Success("Request Created Successfully");
                _notyf.Custom("Account Set-up details have been sent to the user email");

            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
            }
            return View(fmfr);
        }
        #endregion

        #region PATIENT REQUEST 
        [HttpGet]
        public IActionResult create_patient_request()
        {
            PatientModel patient = new()
            {
                Regions = _context.Regions.ToList()
            };
            return View(patient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult create_patient_request(PatientModel pm)
        {
            string path = _environment.WebRootPath;
            if (ModelState.IsValid)
            {
                var uniqueid = Guid.NewGuid().ToString();
                _patient_Request.PRequest(pm, uniqueid, path);
                return RedirectToAction("create_patient_request", "Guest");
            }

            pm.Regions = _context.Regions.ToList();
            return View(pm);
        }
        #endregion

        #region LOGIN PAGE METHODS

        #region Login
        public IActionResult login_page()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

HalloDoc Project/Controllers/ProviderController.cs
using DAL.DataContext;
using DAL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using static HalloDoc_Project.Extensions.Enumerations;

namespace HalloDoc_Project.Controllers
{
    [CustomAuthorize("Physician")]

    public class ProviderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProviderController(ApplicationDbContext context)
        {
            _context=context;
        }
        public IActionResult ProviderDashboard()
        {
            return View();
        }
        //public IActionResult Dashboard()
        //{
        //    string? phyName = HttpContext.Request.Headers.Where(x => x.Key == "userName").FirstOrDefault().Value;
        //    int phyId = Convert.ToInt32(HttpContext.Request.Headers.Where(x => x.Key == "userId").FirstOrDefault().Value);

        //    if (phyName == null)
        //    {
        //        return RedirectToAction("submit_request_page", "Guest");
        //    }


        //    ProviderDashboardViewModel model = new ProviderDashboardViewModel();
        //    model.UserName = phyName;
        //    model.physicians = _context.Physicians;
        //    model.regions = _context.Regions;
        //    model.NewReqCount = _context.Requests.Count(r => r.Physicianid == phyId && r.Status == (short)RequestStatus.Unassigned);
        //    model.PendingReqCount = _context.Requests.Count(r => r.Physicianid == phyId && r.Status == (short)RequestStatus.Accepted);
        //    model.ActiveReqCount = _context.Requests.Count(r => r.Physicianid == phyId && ((r.Status == (short)RequestStatus.MDEnRoute) || (r.Status == (short)RequestStatus.MDOnSite)));
        //    model.ConcludeReqCount = _context.Requests.Count(r => r.Physicianid == phyId && r.Status == (short)RequestStatus.Conclude);
        //    model.casetags = _context.Casetags;

        //    return View("Header/Dashboard", model);

        //}
        //[HttpPost]
        //public async Task<ActionResult> PartialTable(int status, int page, int typeFilter, string searchFilter, int regionFilter)
        //{

        //    HttpContext.Session.SetInt32("currentStatus", status);
        //    HttpContext.Session.SetInt32("currentPage", page);
        //    HttpContext.Session.SetInt32("currentTypeFilter", typeFilter);
        //    HttpContext.Session.SetInt32("currentRegionFilter", regionFilter);
        //    HttpContext.Session.SetString("currentSearchFilter", searchFilter ?? "");

        //    int phyId = Convert.ToInt32(HttpContext.Request.Headers.Where(x => x.Key == "userId").FirstOrDefault().Value);

        //    int pageNumber = 1;
        //    if (page > 0)
        //    {
        //        pageNumber = page;
        //    }

        //    DashboardFilter filter = new DashboardFilter()
        //    {
        //        RequestTypeFilter = typeFilter,
        //        PatientSearchText = searchFilter,
        //        RegionFilter = regionFilter,
        //        pageNumber = pageNumber,
        //        pageSize = 5,
        //        status = status,
        //    };

        //    List<ProviderRequestViewModel> RequestList = await GetProviderRequests(filter, phyId);

        //    ProviderDashboardViewModel model = new ProviderDashboardViewModel();
        //    model.RequestList = RequestList;
        //    model.DashboardStatus = status;
        //    model.CurrentPage = pageNumber;
        //    model.filterOptions = filter;

        //    return PartialView("ProviderDashboardPartialTable", model);
        //}

        //public async Task<List<ProviderRequestViewModel>> GetProviderRequests(DashboardFilter dashboardParams, int physicianId)
        //{
        //    int pageNumber = dashboardParams.pageNumber;

        //    if (dashboardParams.pageNumber < 1)
        //    {
        //        pageNumber = 1;
        //    }

        //    List<short> validRequestTypes = new List<short>();
        //    switch (dashboardParams.status)
        //    {
        //        case (int)DashboardStatus.New:
        //            validRequestTypes.Add((short)RequestStatus.Unassigned);
        //            break;
        //        case (int)DashboardStatus.Pending:
        //            validRequestTypes.Add((short)RequestStatus.Accepted);
        //            break;
        //        case (int)DashboardStatus.Active:
        //            validRequestTypes.Add((short)RequestStatus.MDEnRoute);
        //            validRequestTypes.Add((short)RequestStatus.MDOnSite);
        //            break;
        //        case (int)DashboardStatus.Conclude:
        //            validRequestTypes.Add((short)RequestStatus.Conclude);
        //            break;
        //        case (int)DashboardStatus.ToClose:
        //            validRequestTypes.Add((short)RequestStatus.Cancelled);
        //            validRequestTypes.Add((short)RequestStatus.CancelledByPatient);
        //            validRequestTypes.Add((short)RequestStatus.Closed);

        //            break;
        //        case (int)DashboardStatus.Unpaid:
        //            validRequestTypes.Add((short)RequestStatus.Unpaid);
        //            break;
        //    }

        //    var query = (from r in _context.Requests
        //                 where (r.Physicianid == physicianId)
        //                 && validRequestTypes.Contains(r.Status)
        //                 join rc in _context.Requestclients on r.Requestid equals rc.Requestid
        //                 where (dashboardParams.RequestTypeFilter == 0 || r.Requesttypeid == dashboardParams.RequestTypeFilter)
        //                 && (dashboardParams.RegionFilter == 0 || rc.Regionid == dashboardParams.RegionFilter)
        //                 && (string.IsNullOrEmpty(dashboardParams.PatientSearchText) || (rc.Firstname + " " + rc.Lastname).ToLower().Contains(dashboardParams.PatientSearchText.ToLower()))
        //                 join form in _context.Encounterforms on r.Requestid equals form.Requestid into formGroup
        //                 from formItem in formGroup.DefaultIfEmpty()
        //                 select new ProviderRequestViewModel
        //                 {
        //                     IsHouseCall = (r.Status == (int)RequestStatus.MDOnSite) ? true : false,
        //                     RequestId = r.Requestid,
        //                     Email = rc.Email,
        //                     PatientName = rc.Firstname + " " + rc.Lastname,
        //                     RequestType = r.Requesttypeid,
        //                     PatientPhone = rc.Phonenumber,
        //                     Phone = r.Phonenumber,
        //                     Address = rc.Address,
        //                     IsFinalize = formItem.Isfinalize ? true : false,
        //                 }).ToList();
        //    return query;

        //}

    }

}

HalloDoc Project/Views/Guest/AccessDenied.cshtml
<h3>Access Denied</h3>

HalloDoc Project/Views/Guest/PatientAccountSetupPage.cshtml
@model PatientSetupViewModel
@{
    Layout = "_login_and_forgotpassword";
}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Patient Account Setup Page</title>
    <link rel="stylesheet" href="~/css/login_page_css.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>


    <div class="background"></div>
    <div class=" row justify-content-end container-fluid align-top">
        <div class="col-1 ">
            <button class="btn btn-outline-info" onclick="darkMode()" type="button">
                <img src="/SRS Screen Shorts/dark_mode_black_24dp.svg" class=" " alt="dark-mode-icon">
            </button>
        </div>
    </div>
    <div class="row align-middle container-fluid justify-content-center">
        <div class="container-fluid col-lg-6 col-md-7  col-sm-8 col-9">
            <div class="row">
                <img src="/SRS Screen Shorts/HalloDoc LOGO.png" class="img-fluid " alt="logo here">
            </div>
            <div class="row">
                <div style="font-size:45px;">Set Up Password</div>
            </div>
            <form method="post" asp-action="PatientAccountSetupPage" asp-controller="Guest">
                <div class="row mt-3">
                    <div class=" d-flex align-items-center form-control form-floating mb-3 p-1">
                        <input type="text" disabled asp-for="UserName" class="form-control input_field" id="PatientProfileSetupInputUsername" placeholder=""
                               style="border: none;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                             class="bi bi-person" viewBox="0 0 16 16">
                            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
                        </svg>
                        <label for="PatientProfileSetupInputUsername">Username</label>
                    </div>
                    <div class="d-flex align-items-center form-control form-floating mb-3 p-1">
                        <input type="password" asp-for="Password" class="form-control input_field" id="PatientProfileSetupInputPassword" placeholder=""
                               style="border:none">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                             class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0" />
                        </svg>
                        <label for="PatientProfileSetupInputPassword" >Password</label>
                    </div>
                    <div class="d-flex align-items-center form-control form-floating mb-3 p-1">
                        <input type="password" asp-for="ConfirmPassword" class="form-control input_field" id="PatientProfileSetupInputConfirmPassword" placeholder=""
                               style="border:none">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                             class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0" />
                        </svg>
                        <label for="PatientProfileSetupInputConfirmPassword" >Confirm Password</label>
                    </div>
                </div>

                <div class="mb-3 justify-content-center d-flex">
                    <button type="submit" class=" btn px-5 button bg-info border-0 p-2 ">
                        <span style="color:white">Set-up Password</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row align-items-center justify-content-center">

        <footer class="py-5  position-fixed bottom-0">

            <div class="justify-content-center d-flex align-items-end">
                <a href="" class="text-decoration-none"><span class=" text-muted">Terms of Conditions</span></a>
                <span class="px-2 text-muted " style="color: grey;">|</span>
                <a href="" class="text-decoration-none "><span class="text-muted">Privacy Policy</span></a>
            </div>

        </footer>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</body>
</html>

HalloDoc Project/Views/Guest/PrivacyPolicy.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <h1>Privacy Policy</h1>
    <small>Note that all the data taken by this website will be safely stored on our servers and will not be shared with anyone outside our organization.</small>   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

HalloDoc Project/Views/Guest/TermsAndConditions.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <h1>Terms and Conditions for the Hallo Doc Website are written on this page!</h1>
    <small>Kindly read all the terms and conditions carefully.</small>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

HalloDoc Project/Views/Guest/submit_request_page.cshtml
@{
    Layout = "_Layout";
}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/submit_request.css" />
</head>
<body>
    <nav class="navbar navigationbar navbar-light shadow  rounded w-100">
        <div class="w-100 align-items-center" style="display:contents;">
            <div class="d-none  d-md-block">
                <a href="#" class="navbar-brand">
                    <img src="/SRS Screen Shorts/HalloDoc LOGO.png" alt="" height="80vh">
                </a>
            </div>
            <div class="justify-content-end float-end me-3">
                <button class="btn" onclick="darkMode()">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#10bce9" class="bi bi-moon-fill"
                         viewBox="0 0 16 16">
                        <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278" />
                    </svg>
                </button>
            </div>
        </div>
    </nav>
    <div class="">
        <div class="bg"></div>
        <div class=" d-flex flex-column justify-content-center align-items-center" style="height:83vh">
            <div class="d-block d-md-none  ">
                <img src="/SRS Screen Shorts/HalloDoc LOGO.png" class="img-fluid" style="min-width:200px" alt="">
            </div>

            <div class="col-md-6 col-lg-4 col-sm-8 col-10 border d-flex align-items-center  m-2 ">
                <button onclick="window.location.href='/Guest/patient_submit_request_screen'" class="btno1 py-3 rounded w-100 ">
                    SUBMIT A REQUEST
                </button>
            </div>
            <div class="col-md-6 col-lg-4 col-sm-8 col-10 border rounded m-2 ">
                <button onclick="window.location.href = '/Guest/login_page';" class=" btno2 py-3 w-100 px- rounded">
                    REGISTERED PATIENTS
                </button>
            </div>
            <div class="col-md-6 col-lg-4 col-sm-8 col-10 border rounded m-2 ">
                <a asp-action="ProviderDashboard" asp-controller="Provider" class=" btno2 py-3 w-100 px- rounded">
                    ADMIN DASHBOARD
                </a>
            </div>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>
</body>
</html>